"""
AuthentiPix — Robustness Layer 10-Image Test Runner

Purpose:
    Run the existing AuthentiPix analysis pipeline against the 10-image
    robustness test set and print a clear forensic summary.

IMPORTANT:
    - This file contains NO ground-truth labels.
    - It does NOT decide whether an image is real, AI-generated, or a screenshot.
    - It only runs the existing production pipeline and displays its results.
    - Do NOT modify Phase 1, Phase 2, Phase 3A, or the Robustness implementation
      from this test file.

Expected files in the project root:

    sample1.jpg
    sample2.png
    sample3.png
    sample4.jpg
    sample5.png
    sample6.png
    sample7.png
    sample8.jpg
    sample9.png
    sample10.jpg

Run from the AuthentiPix project root:

    python TEMP_AI_REAL_TEST.py
"""

from pathlib import Path
import json
import subprocess
import sys


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent

TEST_IMAGES = [
    "sample1.jpg",
    "sample2.png",
    "sample3.png",
    "sample4.jpg",
    "sample5.png",
    "sample6.png",
    "sample7.png",
    "sample8.jpg",
    "sample9.png",
    "sample10.jpg",
]


# ============================================================
# HELPERS
# ============================================================

def print_separator(char="=", length=100):
    print(char * length)


def get_value(data, *keys, default="N/A"):
    """
    Safely retrieve a nested value from a dictionary.

    Example:
        get_value(data, "robustness", "actual_format")
    """
    current = data

    for key in keys:
        if not isinstance(current, dict):
            return default

        if key not in current:
            return default

        current = current[key]

    return current


def find_result_json(image_path):
    """
    Locate the JSON result generated by run_analysis.py.

    The existing pipeline may use one of several naming conventions,
    so check the common possibilities without changing the pipeline.
    """

    stem = image_path.stem

    candidates = [
        PROJECT_ROOT / f"analysis_result_{stem}.json",
        PROJECT_ROOT / f"{stem}_analysis_result.json",
        PROJECT_ROOT / "analysis_results" / f"analysis_result_{stem}.json",
        PROJECT_ROOT / "results" / f"analysis_result_{stem}.json",
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return None


def run_single_image(image_name):
    """
    Run the existing production runner for one image.

    IMPORTANT:
        We do not reproduce the analysis logic here.
        run_analysis.py remains the single source of truth.
    """

    image_path = PROJECT_ROOT / image_name

    if not image_path.exists():
        return {
            "success": False,
            "error": f"File not found: {image_name}",
            "result": None,
        }

    print()
    print_separator("-")
    print(f"RUNNING: {image_name}")
    print_separator("-")

    try:
        completed = subprocess.run(
            [
                sys.executable,
                str(PROJECT_ROOT / "run_analysis.py"),
                str(image_path),
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )

        if completed.returncode != 0:
            print("STATUS: FAILED")
            print()
            print(completed.stderr.strip())

            return {
                "success": False,
                "error": completed.stderr.strip(),
                "result": None,
            }

        result_file = find_result_json(image_path)

        if result_file is None:
            print("STATUS: PIPELINE COMPLETED")
            print("WARNING: Result JSON could not be located.")

            return {
                "success": True,
                "error": "Result JSON not found",
                "result": None,
            }

        try:
            with result_file.open("r", encoding="utf-8") as f:
                result = json.load(f)

            return {
                "success": True,
                "error": None,
                "result": result,
            }

        except Exception as exc:
            return {
                "success": False,
                "error": f"Could not read result JSON: {exc}",
                "result": None,
            }

    except Exception as exc:
        return {
            "success": False,
            "error": str(exc),
            "result": None,
        }


def extract_summary(image_name, result):
    """
    Extract only reporting fields.

    No classification logic is performed here.
    """

    filename_extension = Path(image_name).suffix.lower()

    # --------------------------------------------------------
    # Try common top-level / nested locations used by the
    # AuthentiPix report schema.
    # --------------------------------------------------------

    actual_format = (
        get_value(result, "actual_format", default=None)
        or get_value(result, "format", "actual_format", default=None)
        or get_value(result, "robustness", "actual_format", default=None)
        or get_value(result, "format_detection", "actual_format", default=None)
        or "N/A"
    )

    mismatch = (
        get_value(result, "format_mismatch_detected", default=None)
        if "format_mismatch_detected" in result
        else get_value(result, "robustness", "format_mismatch_detected", default="N/A")
    )

    exif = (
        get_value(result, "exif", default=None)
        or get_value(result, "metadata", "exif", default=None)
    )

    c2pa = (
        get_value(result, "c2pa", default=None)
        or get_value(result, "metadata", "c2pa", default=None)
    )

    provenance_assessment = (
        get_value(result, "provenance_assessment", default=None)
        or get_value(result, "robustness", "provenance_assessment", default=None)
        or get_value(result, "assessment", "provenance_assessment", default=None)
        or "N/A"
    )

    final_assessment = (
        get_value(result, "final_synthesized_assessment", default=None)
        or get_value(result, "synthesized_assessment", default=None)
        or get_value(result, "robustness", "synthesized_assessment", default=None)
        or "N/A"
    )

    evidence_tier = (
        get_value(result, "evidence_tier", default=None)
        or get_value(result, "robustness", "evidence_tier", default=None)
        or "N/A"
    )

    original_source = (
        get_value(result, "original_source", default=None)
        or get_value(result, "robustness", "original_source", default=None)
        or "N/A"
    )

    recapture = (
        get_value(result, "candidate_recapture_indicators", default=None)
        or get_value(result, "recapture_indicators", default=None)
        or get_value(
            result,
            "robustness",
            "candidate_recapture_indicators",
            default=None,
        )
        or "N/A"
    )

    return {
        "image": image_name,
        "extension": filename_extension,
        "actual_format": actual_format,
        "mismatch": mismatch,
        "exif": "YES" if exif else "NO",
        "c2pa": "YES" if c2pa else "NO",
        "recapture": recapture,
        "provenance": provenance_assessment,
        "assessment": final_assessment,
        "tier": evidence_tier,
        "original_source": original_source,
    }


# ============================================================
# MAIN TEST
# ============================================================

def main():

    print()
    print_separator("=")
    print("AUTHENTIPIX — ROBUSTNESS LAYER 10-IMAGE TEST")
    print_separator("=")

    print()
    print("Purpose:")
    print("  Validate the existing Robustness pipeline on all 10 images.")
    print()
    print("Important:")
    print("  No ground-truth labels are used.")
    print("  No AI/REAL/SCREENSHOT assumptions are hard-coded.")
    print("  Results are generated by the existing AuthentiPix pipeline.")
    print()

    print_separator("-")
    print("TEST SET")
    print_separator("-")

    for index, image in enumerate(TEST_IMAGES, start=1):
        exists = (PROJECT_ROOT / image).exists()
        status = "FOUND" if exists else "MISSING"
        print(f"{index:02d}. {image:<20} [{status}]")

    print()

    # --------------------------------------------------------
    # Run all images
    # --------------------------------------------------------

    summaries = []
    failures = []

    for image_name in TEST_IMAGES:

        execution = run_single_image(image_name)

        if not execution["success"]:
            failures.append(
                {
                    "image": image_name,
                    "error": execution["error"],
                }
            )
            continue

        if execution["result"] is None:
            failures.append(
                {
                    "image": image_name,
                    "error": execution["error"],
                }
            )
            continue

        summary = extract_summary(
            image_name,
            execution["result"],
        )

        summaries.append(summary)

    # ========================================================
    # FINAL SUMMARY TABLE
    # ========================================================

    print()
    print_separator("=")
    print("ROBUSTNESS ANALYSIS — FINAL SUMMARY")
    print_separator("=")

    headers = [
        "Image",
        "Ext",
        "Actual",
        "Mismatch",
        "EXIF",
        "C2PA",
        "Recapture",
        "Provenance",
        "Assessment",
        "Tier",
        "Original Source",
    ]

    print(
        f"{headers[0]:<14}"
        f"{headers[1]:<7}"
        f"{headers[2]:<9}"
        f"{headers[3]:<10}"
        f"{headers[4]:<6}"
        f"{headers[5]:<6}"
        f"{headers[6]:<34}"
        f"{headers[7]:<24}"
        f"{headers[8]:<38}"
        f"{headers[9]:<18}"
        f"{headers[10]:<30}"
    )

    print_separator("-")

    for row in summaries:

        print(
            f"{str(row['image']):<14}"
            f"{str(row['extension']):<7}"
            f"{str(row['actual_format']):<9}"
            f"{str(row['mismatch']):<10}"
            f"{str(row['exif']):<6}"
            f"{str(row['c2pa']):<6}"
            f"{str(row['recapture']):<34}"
            f"{str(row['provenance']):<24}"
            f"{str(row['assessment']):<38}"
            f"{str(row['tier']):<18}"
            f"{str(row['original_source']):<30}"
        )

    # ========================================================
    # FAILURES
    # ========================================================

    print()

    if failures:

        print_separator("!")
        print("PIPELINE FAILURES")
        print_separator("!")

        for failure in failures:
            print(f"Image: {failure['image']}")
            print(f"Error: {failure['error']}")
            print()

    else:

        print_separator("-")
        print("PIPELINE STATUS")
        print_separator("-")

        print(f"Images requested : {len(TEST_IMAGES)}")
        print(f"Images analyzed  : {len(summaries)}")
        print(f"Failures         : {len(failures)}")

    # ========================================================
    # IMPORTANT FORENSIC NOTES
    # ========================================================

    print()
    print_separator("=")
    print("FORENSIC INTERPRETATION NOTES")
    print_separator("=")

    print(
        "1. Missing EXIF/C2PA does NOT mean AI-generated."
    )

    print(
        "2. Missing EXIF/C2PA does NOT mean real/camera-origin."
    )

    print(
        "3. Screenshot/recapture-like indicators describe the CURRENT FILE."
    )

    print(
        "4. Screenshot evidence does NOT establish the original image's provenance."
    )

    print(
        "5. Camera-consistent indicators are NOT equivalent to confirmed physical camera capture."
    )

    print(
        "6. Format mismatch indicates a transformation/extension inconsistency,"
        " not an AI/real classification."
    )

    print(
        "7. All conclusions must come from the production pipeline,"
        " not from this test runner."
    )

    # ========================================================
    # FINAL STATUS
    # ========================================================

    print()
    print_separator("=")

    if len(summaries) == len(TEST_IMAGES):

        print("ROBUSTNESS 10-IMAGE TEST: COMPLETED")
        print("All 10 images were processed successfully.")

    else:

        print("ROBUSTNESS 10-IMAGE TEST: INCOMPLETE")
        print(
            f"{len(summaries)} / {len(TEST_IMAGES)} images processed successfully."
        )

    print_separator("=")
    print()


if __name__ == "__main__":
    main()
